on:
  workflow_dispatch:

jobs:
  sync:
    name: "Sync Submodules"
    runs-on: ubuntu-latest
    
    defaults:
      runs:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.SKIS_BOT_PAT }}
        submodules: true
    
    - name: Submodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive
    
    - name: Commit Update
      run: |
        git config --global user.name "SKIS [bot]"
        git config --global user.email ${{ secrets.SKIS_BOT_MAIL }}
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "[sync] Submodules updated" && git push || echo "No changes to commit"